USE cinetrack_db;


CREATE TABLE usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL,
password VARCHAR(255) NOT NULL,
imagen_perfil VARCHAR(255),
fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
rol VARCHAR(20) NOT NULL DEFAULT 'USER',
activo BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE generos (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
descripcion VARCHAR(255)
);


CREATE TABLE peliculas (
id INT AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(150) NOT NULL,
descripcion TEXT NOT NULL,
duracion INT NOT NULL,
anio INT NOT NULL,
url_imagen VARCHAR(255),
url_video VARCHAR(255),
genero_id INT NOT NULL,
destacada BOOLEAN NOT NULL DEFAULT FALSE,
fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE usuario_generos (
id INT AUTO_INCREMENT PRIMARY KEY,
usuario_id INT NOT NULL,
genero_id INT NOT NULL
);


CREATE TABLE historial_visualizacion (
id INT AUTO_INCREMENT PRIMARY KEY,
usuario_id INT NOT NULL,
pelicula_id INT NOT NULL,
fecha_ultima_visualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
progreso_segundos INT NOT NULL DEFAULT 0,
completada BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE TABLE mi_lista (
id INT AUTO_INCREMENT PRIMARY KEY,
usuario_id INT NOT NULL,
pelicula_id INT NOT NULL,
fecha_agregado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
